// Code generated by cmd/cgo; DO NOT EDIT.

//line AnalyGoAndC.go:1:1
package main
// static int add(int a,int b){
//  return a+b;
//}
import _ "unsafe"
import "fmt"

func main() {
	fmt.Print(( /*line :9:12*/_Cfunc_add /*line :9:16*/)(3,4))
}